import { AIModel } from './types';

export const models: AIModel[] = [
  {
    id: 'claude-opus-4-5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    icon: '🧠',
    description: 'Best reasoning & deep analysis',
    category: 'Expert Reasoning',
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xai',
    icon: '⚡',
    description: 'Fast & witty reasoning',
    category: 'Fast Reasoning',
  },
  {
    id: 'video-generation',
    name: 'Video Generator',
    provider: 'video-ai',
    icon: '🎥',
    description: 'Generate videos from text',
    category: 'Creative',
  },
  {
    id: 'x-ai/grok-4.1-fast',
    name: 'Grok 4.1 Fast',
    provider: 'xai',
    icon: '🚀',
    description: 'Connects to external APIs',
    category: 'Agentic',
  },
  {
    id: 'gpt-5.2',
    name: 'GPT 5.2',
    provider: 'openai',
    icon: '🤖',
    description: 'Expert reasoning & coding',
    category: 'Coding Expert',
  },
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro',
    provider: 'google',
    icon: '💎',
    description: 'Multimodal coding expert',
    category: 'Coding Expert',
  },
  {
    id: 'gemini-2-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    icon: '✨',
    description: 'Speed & multimodal power',
    category: 'Ultra-Fast',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    icon: '🤖',
    description: 'Versatile & powerful',
    category: 'Balanced',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    icon: '🔍',
    description: 'Deep reasoning chains',
    category: 'Chain-of-Thought',
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'mistral',
    icon: '🌪️',
    description: 'French excellence',
    category: 'Balanced',
  },
];
